### ISSUE TITLE
Support for actix-web 3

### ISSUE THREAD

**Issue by blasrodri** [elmarx/actix-slog#2]
Hi! Thanks for making this :).
I have a project that is running on actin-web 3. I'd like to be able to use this crate there.

I've made a failed attempt to port it here:
https://github.com/blasrodri/actix-slog/pull/1

Perhaps you could help me out? :) Thanks!

**Comment by elmarx** [comment]
Hey @blasrodri it's nice that you're interested in this little crate.

I just pushed a new branch *actix-web-3*, you should be able to try it out with adding the following to your `Cargo.toml`.

```
 [patch.crates-io] 
 openssl = { git = 'https://github.com/elmarx/actix-slog.git', branch='actix-web-3' } 
```

The examples from this repo both work, although I did not yet try this update (and actix-web 3) on my real-world projects, I'm pretty positive that it should work.

I adapted the changes from https://github.com/actix/actix-web/blob/master/src/middleware/logger.rs — which is the base for actix-slog anyway. 
To be honest, I have only a vague idea how this `pin_project` works and why it's necessary… ;)

**Comment by blasrodri** [comment]
Thanks! I'll give it a look these days :). Highly appreciated.
